empInfo([{
         	"firstName":"Dipak",
         	"lname":"Deshmukh",
         },
         {
         	"firstName":"Rohit",
         	"lname":"Gund",
         },
         {
         	"firstName":"Ashok",
         	"lname":"pagare",
         },
         {
            "firstName":"Sagar",
            "lname":"Ravate",
         },
         {
            "firstName":"Mahesh",
            "lname":"Deole",
         },
         {
            "firstName":"Rajesh",
            "lname":"kharat",
         },
         {
            "firstName":"Rajesh",
            "lname":"Mehta",
         }
       ]);   
